PortfolioService/Controllers/SetAlertController.cs
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Queue;
using PortfolioService.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PortfolioService.Controllers {
    public class SetAlertController : Controller {
        [HttpGet]
        public ActionResult Index() {
            SetAlertViewModel model = new SetAlertViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SetAlert(SetAlertViewModel model) {
            if (Session["UserEmail"] == null) {
                return RedirectToAction("LogIn", "Account");
            }

            if (ModelState.IsValid) {
                CloudStorageAccount storageAccount = CloudStorageAccount.Parse("UseDevelopmentStorage=true");
                CloudQueueClient queueClient = storageAccount.CreateCloudQueueClient();
                CloudQueue queue = queueClient.GetQueueReference("alarms");
                await queue.CreateIfNotExistsAsync();

                string userEmail = (string)Session["UserEmail"];

                string messageContent = $"{model.CryptocurrencyName}|{model.AlertThreshold}|{userEmail}|{model.IsLowerTreshold}";
                CloudQueueMessage message = new CloudQueueMessage(messageContent);
                await queue.AddMessageAsync(message);

                ViewBag.Message = "Alert has been set successfully!";

                return RedirectToAction("Index", "Portfolio");
            }

            return View(model);
        }
    }
}

PortfolioService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Portfolio</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <header>
        <nav>
            @if (Session["UserEmail"] != null)
            {
                <ul>
                    <li>@Html.ActionLink("Portfolio", "Index", "Portfolio")</li>
                    <li>@Html.ActionLink("Add transaction", "AddTransaction", "Portfolio")</li>
                    <li>@Html.ActionLink("Search", "Index", "Search")</li>
                    <li>@Html.ActionLink("Set Alert", "Index", "SetAlert")</li>
                    <li>@Html.ActionLink("Edit profile", "EditProfile", "Account")</li>
                    <li>@Html.ActionLink("Log out", "Logout", "Account")</li>
                </ul>
            }
        </nav>
    </header>
    <div class="container">
        @RenderBody()
    </div>
    <footer>
        <p>&copy; @DateTime.Now.Year - Portfolio Service</p>
    </footer>

    @RenderSection("scripts", required: false)

</body>
</html>